### ISSUE TITLE
Creativecommons is not included as a node

### ISSUE THREAD

**Issue by MercureTony** [creativecommons/cccatalog-dataviz#23]
I noticed that if a user may want to search for the Creative Common node on the graph, they won't be able. I believe the reason is that most other nodes are connected to it and it was voluntarily removed from other nodes? 
I was wondering if there was an approach to integrate this node without rendering a skewed graph.

```
 - OS: Windows 10.0.17763
 - Browser:  Chrome
 - Version 80.0.3987.149
```

**Comment by soccerdroid** [comment]
Yes, that's the reason why we did not include Creative Commons as a node. This is actually not an issue or bug, because what we are trying to check is how the commons interact between them. We already know that they are connected to CC, and other fields like the number of images or licenses, already give us information about their interaction with CC.  If you think this is an issue and we are skipping something important, please let us know.
